language: python

sudo: required
dist: xenial

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq

install:
 - sudo apt-get install -qq build-essential gcc-5-base gcc-5 gfortran-5 libblas-dev liblapack-dev python-pip
 - sudo pip install numpy -U
 - sudo pip install scipy -U

 - sudo python setup.py build --fcompiler=gnu95
 - sudo python setup.py install

before_script:
  - cd ${TRAVIS_BUILD_DIR}

script: nosetests
