language: python

sudo: required
dist: trusty

python:
  - "2.7"
  - "3.5"

before_install:
  - sudo apt-get update -qq

install:
 - sudo apt-get install -qq build-essential gcc gfortran libblas-dev liblapack-dev python3-pip
 - sudo apt-get install -qq gcc-4.8 gfortran-4.8

 - echo ${TRAVIS_PYTHON_VERSION}
 - |
   if [ ${TRAVIS_PYTHON_VERSION} = "3.4" ]; then
       sudo pip3 install numpy -U
       python3 setup.py build
       python3 setup.py install
   elif [ ${TRAVIS_PYTHON_VERSION} = "2.7" ]; then
       sudo pip2 install numpy -U
       python2 setup.py build
       python2 setup.py install
   fi


before_script:
 - cd ${TRAVIS_BUILD_DIR}
 - export PYTHONPATH=/usr/local/lib/python${TRAVIS_PYTHON_VERSION}/dist-packages:${PYTHONPATH}

script:
 - nosetests -v tests/*.py
