language: python

sudo: required
dist: trusty

python:
  - "2.7"
  - "3.5"

before_install:
  - sudo apt-get update -qq

install:
    - sudo apt-get install -qq build-essential gcc gfortran libblas-dev liblapack-dev python3-pip
 - sudo apt-get install -qq gcc-4.8 gfortran-4.8

 - sudo pip2 install numpy -U
 - sudo pip3 install numpy -U

 - sudo python setup.py build
 - sudo python setup.py install

before_script:
 - cd ${TRAVIS_BUILD_DIR}
 - export PYTHONPATH=/usr/local/lib/python${TRAVIS_PYTHON_VERSION}/dist-packages:${PYTHONPATH}

script:
 - nosetests -v tests/*.py
