language: python

sudo: required
dist: trusty

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq

install:
 - sudo apt-get install -qq build-essential gcc gfortran libblas-dev liblapack-dev python-numpy python-scipy
 - sudo apt-get install -qq gcc-4.8 gfortran-4.8

 - sudo python setup.py build
 - sudo python setup.py install

 - export PYTHONPATH=/usr/local/lib/python${TRAVIS_PYTHON_VERSION}/dist-packages:${PYTHONPATH}
 - echo ${PYTHONPATH}
 - echo ${TRAVIS_PYTHON_VERSION}

before_script:
  - cd ${TRAVIS_BUILD_DIR}

script: nosetests
